[package]
name = "lendcraft-deployer-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { version = "0.8.4" }

[dev_dependencies]
soroban-sdk = { version = "0.8.4", features = ["testutils"] }
